# -*- coding: utf-8 -*-
"""brain tumor frontend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJA9VVYZ-G8DktB3utzkviDpcsyud2hO
"""

!pip install gradio tensorflow pillow numpy

import gradio as gr
import tensorflow as tf
import numpy as np
from PIL import Image
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

# Load model
model = tf.keras.models.load_model("bestmodel_finetuned.keras", compile=False)


class_names = ["glioma", "meningioma", "notumor", "pituitary"]

def predict(image):
    image = image.resize((224, 224))
    image = np.array(image, dtype=np.float32)
    image = preprocess_input(image)
    image = np.expand_dims(image, axis=0)

    prediction = model.predict(image)[0]
    predicted_index = np.argmax(prediction)
    predicted_class = class_names[predicted_index]
    confidence = prediction[predicted_index] * 100

    # Build result string showing all class probabilities
    result = f"**Predicted: {predicted_class.upper()}** ({confidence:.1f}% confidence)\n\n"
    result += "### All Probabilities:\n"
    for name, prob in zip(class_names, prediction):
        bar = "█" * int(prob * 20)
        result += f"- `{name:12s}` {prob*100:5.1f}%  {bar}\n"

    return result

interface = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="pil"),
    outputs="markdown",
    title="🧠 Brain Tumor Detection",
    description="Upload MRI Image"
)

interface.launch(share=True)